OpenDataPlane/odp-dpdk

platform/linux-dpdk/Makefile.am

Use correct path for all miniz library source files.

[PATCH v2] linux-dpdk: fix miniz library file paths

---

config/odp-linux-dpdk.conf
m4/odp_dpdk.m4
platform/linux-dpdk/Makefile.am
platform/linux-dpdk/README
platform/linux-dpdk/include/odp_eventdev_internal.h
platform/linux-dpdk/include/odp_packet_io_internal.h
platform/linux-dpdk/m4/configure.m4
platform/linux-dpdk/odp_init.c
platform/linux-dpdk/odp_packet_dpdk.c
platform/linux-dpdk/odp_queue_eventdev.c
platform/linux-dpdk/odp_queue_if.c
platform/linux-dpdk/odp_schedule_eventdev.c
platform/linux-dpdk/odp_schedule_if.c
platform/linux-dpdk/odp_thread.c

Add DPDK eventdev based new scheduler and queue implementations. The initial
implementation has been validated using only the standard software eventdev
poll mode driver with DPDK v18.11.
To use eventdev one must set ODP_SCHEDULER environment variable to
"eventdev" and provide the necessary platform parameters to DPDK.

[PATCH v2] linux-dpdk: initial experimental eventdev support

---

platform/linux-dpdk/include/odp_eventdev_internal.h
platform/linux-dpdk/odp_queue_eventdev.c
platform/linux-dpdk/odp_schedule_eventdev.c

ODP_SCHED_PRIO_HIGHEST == RTE_EVENT_DEV_PRIORITY_LOWEST, so ODP priority
has to be converted into eventdev priority.

[PATCH v2] linux-dpdk: eventdev: use correct priority value

---

platform/linux-dpdk/odp_packet_dpdk.c

The NIC offload capabilities stored in rte_eth_dev_info.rx_offload_capa/
tx_offload_capa cannot be used per NIC queue. Fix this by doing offload
configurarion using rte_eth_dev_configure().

[PATCH v2] linux-dpdk: pktio: fix rx/tx checksum offload

---

config/odp-linux-dpdk.conf
platform/linux-dpdk/odp_packet_dpdk.c

Add new configuration option 'pktio_dpdk.multicast_en' for selecting
whether multicast Ethernet frames should be received or dropped.
Reported-by: Shen Hanxiao <hanxiao.shen@nokia-sbell.com>
V2:
- Fixed config option comment (Petri)

[PATCH v3] linux-dpdk: pktio: add configuration option for ethernet multicast receipt

---

platform/linux-dpdk/odp_packet_dpdk.c

Previously, calling odp_pktio_start() would always disable promiscuous
mode. Fix this by moving promiscuous mode check into odp_pktio_open().
Reported-by: Marian Beniac <marian.beniac@nokia.com>

[PATCH v1] linux-dpdk: pktio: fix setting promiscuous mode

---

platform/linux-dpdk/README

DPDK crypto device option 'max_nb_sessions' is no longer used. Also, do
miscellaneous clean-ups and use current crypto device naming convention.
Reported-by: Chandan Mohanty <chandan.mohanty@nokia.com>

[PATCH v2] README.DPDK: update crypto pmd chapter

---

platform/linux-dpdk/Makefile.inc
platform/linux-dpdk/test/Makefile.am

Previously, running 'make clean' in an out-of-tree build directory
incorrectly deleted wrapper-script.sh in the source directory.
Reported-by: Carl Wallen <carl.wallen@nokia.com>

[PATCH v2] linux-dpdk: fix out-of-tree build

---

platform/linux-dpdk/odp_crypto.c

DPDK sets max_nb_sessions zero in rte_cryptodev_info_get() when the device
does not have any limit on the number of sessions. It has been so since
DPDK version 18.08 but ODP-DPDK still reports zero max_nb_sessions as
zero max sessions in ODP crypto capability. Fix the problem by taking
max_nb_sessions of a device into account only when it is non-zero.
Signed-off-by: Janne Peltonen <janne.peltonen@nokia.com>

[PATCH v2] linux-dpdk: crypto: fix max_sessions capability

---

platform/linux-dpdk/odp_packet_dpdk.c

Previously, dpdk_init_capability() would crash with a segfault if used port
id was not valid.

[PATCH v2] linux-dpdk: pktio: handle invalid port id cleanly

---

platform/linux-dpdk/README

```
Add instructions for building DPDK 20.11, using meson and ninja. DPDK
19.11 is still the recommended version.
Signed-off-by: Jere Leppänen <jere.leppanen@nokia.com>
```
v2:
- Add PKG_CONFIG_PATH instruction.

[PATCH v3] README.DPDK: add instructions for DPDK 20.11

---

m4/odp_dpdk.m4

When ABI compatibility is disabled DPDK symbols may be visible to the
application.

[PATCH v2] m4: odp_dpdk: fix application linking when using shared dpdk lib

---

m4/odp_dpdk.m4

DPDK PMD driver rte_pmd_octeontx2 has dependency to libm.
Reviewed-by: Petri Savolainen <petri.savolainen@nokia.com>

[PATCH v1] m4: odp_dpdk: add missing libm dependency

---

m4/odp_dpdk.m4

```
On some distros, --disable-new-dtags is not the default, so make it
explicit.
Signed-off-by: Jere Leppänen <jere.leppanen@nokia.com>
```

[PATCH v3] config: use --disable-new-dtags option when using rpath

---

platform/linux-dpdk/odp_crypto.c

Remove redundant memory size in crypto_global_t because the session size is
added at alloc memory in _odp_crypto_init_global().
Signed-off-by: Tim Liu <yliu@sonicwall.com>

[PATCH v2] linux-dpdk: crypto: reduce global memory size

---

.github/workflows/ci-pipeline.yml
platform/linux-dpdk/include/odp/api/plat/packet_flag_inlines.h
scripts/ci/build.sh

Fix warning (-Wconversion) caused by an implicit cast in `odp_packet_has_flow_hash()` return value. The return value could be altered due to an implicit `uint64_t` to `int` conversion.

[PATCH v2] linux-dpdk: packet_flags: fix implicit type conversion

---

platform/linux-dpdk/odp_crypto.c

This change will make linux-dpdk default value to same as linux-generic
value of 4000
Signed-off-by: Vijay Ram Inavolu <vinavolu@marvell.com>

[PATCH v2] linux-dpdk: ipsec: increase default crypto sessions to 4000

---

platform/linux-dpdk/odp_crypto.c

AES-CMAC is not included in crypto capabilities when found in aesni-mb
but it may still be included because some other crypto device supports it.
If aesni-mb device and another device that does support AES-CMAC are
present at the same time, then the aesni-mb device may still get selected
for a session that uses AES-CMAC.
Fix device selection in session creation by excluding AES-CMAC sessions
from the aesni-mb device.
Fixes: cf4d3329d4a9b53663ee27a904ee88f2cd3f50d8
Signed-off-by: Janne Peltonen <janne.peltonen@nokia.com>

[PATCH v2] linux-dpdk: crypto: fix disabling of AES-CMAC with aesni-mb driver

---

config/odp-linux-dpdk.conf
platform/linux-dpdk/m4/odp_libconfig.m4
platform/linux-dpdk/odp_init.c
platform/linux-dpdk/test/crypto.conf
platform/linux-dpdk/test/sched-basic.conf
platform/linux-generic/include/odp_libconfig_internal.h
platform/linux-generic/odp_libconfig.c

Implementation to support pci ports addition using the odp config file
for linux dpdk
Signed-off-by: Vijay Ram Inavolu <vinavolu@marvell.com>

[PATCH v8] linux-dpdk: pktio: add pci ports using config file

---

platform/linux-dpdk/include/odp_pool_internal.h
platform/linux-dpdk/odp_packet.c
platform/linux-dpdk/odp_pool.c

Implementation of external memory pool and packet disassemble and reassemble API.
v1:
- Includes ODP v1.31.0.0 merge draft by Matias.
- The only implementation difference to the earlier PR #139, which is now closed, is that application header is now correctly preserved in packet allocation.
v2:
- Rebase.
- Fix according to comments from @MatiasElo.
v3:
- Rebase.
- Add obj headers and mem headers.
v4:
- Check rte_mempool_ops_enqueue_bulk() and rte_zmalloc() return values.
v5:
- Align rte_mbuf to cache line.
- Check that populated buffers are aligned.

[PATCH v5] linux-dpdk: pool: implement external memory pool

---

configure.ac

Increment implementation version number to reflect the following changes:
- Added implementation for the external memory pool API and related
functions
- Added implementation for the new packet disassemble and reassemble
functions, and related packet buffer accessor functions
- Added support for blacklisting/whitelisting PCI devices in config file
Reviewed-by: Petri Savolainen <petri.savolainen@nokia.com>

[PATCH v1] linux-dpdk: increment library version number to 1.31.0.1

---

.github/workflows/ci-pipeline.yml
config/odp-linux-dpdk.conf
platform/linux-dpdk/Makefile.am
platform/linux-dpdk/include/odp/api/plat/byteorder_inlines_api.h
platform/linux-dpdk/include/odp/api/plat/pktio_inlines_api.h
platform/linux-dpdk/include/odp/api/plat/thread_inlines_api.h
platform/linux-dpdk/include/odp/api/plat/ticketlock_inlines_api.h
platform/linux-dpdk/include/odp_thread_internal.h
platform/linux-dpdk/odp_thread.c
platform/linux-dpdk/odp_timer.c
platform/linux-dpdk/test/alternate-timer.conf

Add new timer implementation using DPDK alternate timer API. The main
difference compared to the standard implementation is that threads can also
process timers set by any other thread. The alternate timer implementation
can be enabled with 'timer.alternate' configuration file option.

[PATCH v3] linux-dpdk: timer: add new implementation using alt dpdk timer

---

config/odp-linux-dpdk.conf
platform/linux-dpdk/m4/odp_libconfig.m4
platform/linux-dpdk/odp_system_info.c
platform/linux-dpdk/test/alternate-timer.conf
platform/linux-dpdk/test/crypto.conf
platform/linux-dpdk/test/sched-basic.conf
platform/linux-generic/include/odp_global_data.h

Add 'system:cpu_hz_static' configuratio option for using a static CPU
frequency value. CPU frequency values returned by odp_cpu_hz() and
odp_cpu_hz_id() calls are read from the OS only once during ODP
initialization. Enabling this option removes system calls from
odp_cpu_hz() and odp_cpu_hz_id() implementations.
NOTE: This option should only be used on systems where CPU frequency
scaling is disabled.

[PATCH v2] linux-dpdk: cpu: add configuration option to use static cpu frequency

---

platform/linux-dpdk/odp_pool.c
test/validation/api/packet/packet.c

Segment size minus headroom might be rounded down by the DPDK driver (e.g.
ixgbe) to the nearest multiple of 1024. Round up the segment size to make
sure that the requested size is going to fit without segmentation.

[PATCH v2] linux-dpdk: pool: round up packet segment sizes to multiples of 1024

---

platform/linux-dpdk/Makefile.am

Fix configuration for linux-generic platform
(--with-platform=linux-generic). Makefile.inc isn't available under
linux-generic platform.
Fixes: https://github.com/OpenDataPlane/odp-dpdk/issues/170

[PATCH v2] linux-dpdk: fix linux-generic configuration error

---

.github/workflows/ci-pipeline.yml
scripts/ci/coverage.sh

Upgrade to Codecov uploader V2 as V1 is being discontinued. The new
uploader doesn't convert *.gcno files into *.gcov files automatically
anymore, so this has to be done now manually in the coverage.sh script.
Reviewed-by: Tuomas Taipale <tuomas.taipale@nokia.com>

[PATCH v2] ci: update codecov uploader version

---

platform/linux-dpdk/README

In the current installation of DPDK-20.11, configuring the location of
DPDK installation to the home directory is a required step. System-wide
installation of DPDK is also an option when ODP-DPDK is not able to link
to DPDK-20.11 by setting of PKG_CONFIG_PATH. This issue was observed on
Arm64 platforms.
Signed-off-by: Malvika Gupta <Malvika.Gupta@arm.com>
Reviewed-by: Govindarajan <govindarajan.mohandoss@arm.com>

[PATCH v2] README: update DPDK-20.11 installation instructions

---

platform/linux-dpdk/odp_crypto.c
platform/linux-dpdk/odp_packet_dpdk.c
platform/linux-dpdk/odp_schedule_eventdev.c

The supported DPDK versions are currently v19.11 and v20.11.

[PATCH v3] linux-dpdk: remove deprecated dpdk code

---

platform/linux-dpdk/dumpconfig
platform/linux-dpdk/dumpconfig/.gitignore
platform/linux-dpdk/dumpconfig/Makefile.am

When making `distclean`, the operation fails while handling
`dumpconfig` as build files (which are currently referenced via a symlink)
are removed in a previous step.
Fix this by creating own `dumpconfig` folder for `linux-dpdk` tree.

[PATCH v2] linux-dpdk: fix distclean

---

platform/linux-dpdk/odp_packet_dpdk.c

Include packets dropped due to RX mbuf allocation failures in
odp_pktio_stats_t.in_discards.

[PATCH v2] linux-dpdk: pktio: include rx mbuf alloc failures in discards counter

---

.github/workflows/ci-pipeline.yml

Update checkpatch-action to v8 to fix failures caused by dubious ownership
in git repository. The issue was caused by GitHub workspace directory being
owned by UID 1001 and the checkpatch-action using UID 0. checkpatch-action
v8 adds the necessary git security exception ('safe.directory') to avoid
the failure.
Reviewed-by: Janne Peltonen <janne.peltonen@nokia.com>

[PATCH v1] github_ci: update checkpatch-action version

---

platform/linux-dpdk/odp_crypto.c

If the packet linearization step fails, the input packet may already have been consumed (if a different output packet was requested) or modified (by the linearization step before it failed). Despite this, the current code always returns an error, indicating that the packet was not consumed.
Fix the bug by returning success for the crypto request and by indicating an error in the crypto result of the output packet.
Signed-off-by: Janne Peltonen <janne.peltonen@nokia.com>

[PATCH v3] linux-dpdk: crypto: fix return status after pkt linearization failure

---

platform/linux-dpdk/odp_crypto.c

These are the same changes as in odp PR 1669 but ported to linux-dpdk:
linux-dpdk: crypto: fix pool checking before metadata copying
linux-dpdk: crypto: reuse input packet as output packet if possible

[PATCH v2] crypto: bug fix and packet allocation optimization

---

platform/linux-dpdk/odp_crypto.c

linux-dpdk: crypto: do not use broken SGL of the aesni_mb device
linux-dpdk: crypto: accept AES-GMAC only with non-null cipher

[PATCH v2] DPDK crypto bug workarounds

---

config/odp-linux-dpdk.conf
platform/linux-dpdk/m4/odp_libconfig.m4
platform/linux-dpdk/odp_packet_dpdk.c
platform/linux-dpdk/test/alternate-timer.conf
platform/linux-dpdk/test/crypto.conf
platform/linux-dpdk/test/process-mode.conf
platform/linux-dpdk/test/sched-basic.conf
platform/linux-dpdk/test/stash-custom.conf

Add new configuration option 'pktio_dpdk:tx_offload_multi_segs' for enabling multi segment transmit offload. This offload may not be supported by some PMDs and may lower maximum throughput, so the options is not enabled by default.

[PATCH v2] linux-dpdk: pktio: add configuration option for enabling multi segment tx

---

platform/linux-dpdk/odp_crypto.c

linux-dpdk: crypto: fix capability query to ignore asymmetric algs
linux-dpdk: crypto: deduplicate some capability matching code
linux-dpdk: crypto: improve returned session creation error codes
linux-dpdk: crypto: partially re-enable aes-xcbc-mac with aesni_mb
linux-dpdk: crypto: partially re-enable aes-cmac with aesni_mb

[PATCH v2] crypto: improvements with alg combinations

---

platform/linux-dpdk/include/event_vector_internal.h
platform/linux-dpdk/include/odp_buffer_internal.h
platform/linux-dpdk/include/odp_event_internal.h
platform/linux-dpdk/include/odp_event_vector_internal.h
platform/linux-dpdk/include/odp_packet_internal.h
platform/linux-dpdk/include/odp_timer_internal.h
platform/linux-dpdk/odp_crypto.c
platform/linux-dpdk/odp_event.c
platform/linux-dpdk/odp_packet.c
platform/linux-dpdk/odp_pool.c
platform/linux-generic/include/odp_event_vector_internal.h
platform/linux-generic/odp_packet_io.c
test/validation/api/traffic_mngr/traffic_mngr.c

Refactor and clean up `_odp_pool_create()`:
- Create all underlying RTE memory pool types with `rte_pktmbuf_pool_create()` instead of using `rte_mempool_create()` for other than packet pools as RTE mbuf is always assumed to precede ODP specific data
- Simplify memory pool object initialization
- Utilize `RTE_MBUF_PRIV_ALIGN` for memory pool element private area alignment
Additionally, remove `struct rte_mbuf` from common event header for potential pool element size savings.
v2:
- Fix checkpatch complaints
- Add debug print to pool creation once RTE mempool arguments have been resolved and calculated
v4:
- Matias' comments
- Removed seemingly unnecessary symbolic link to `linux-generic/include/odp_event_vector_internal.h`

[PATCH v6] linux-dpdk: pool: refactor internal pool creation function

---

platform/linux-dpdk/include/odp_buffer_internal.h
platform/linux-dpdk/include/odp_event_vector_internal.h
platform/linux-dpdk/include/odp_packet_internal.h
platform/linux-dpdk/include/odp_timer_internal.h

Add compile time checks for implementation internal event header sizes. Detect if a size of an event header expands to a new cache line, as this may have significant performance implications.
RTE_CACHE_LINE_SIZE is used instead of ODP_CACHE_LINE_SIZE because in ABI compat mode the values may differ.

[PATCH v2] linux-dpdk: pool: add checks for internal event header sizes

---

config/odp-linux-dpdk.conf
include/odp/api/abi-default/dma_types.h
platform/linux-dpdk/Makefile.am
platform/linux-dpdk/README
platform/linux-dpdk/include-abi/odp/api/abi/dma_types.h
platform/linux-dpdk/include/odp_config_internal.h
platform/linux-dpdk/m4/odp_libconfig.m4
platform/linux-dpdk/odp_dma.c
platform/linux-dpdk/odp_pool.c
platform/linux-dpdk/test/crypto.conf
platform/linux-dpdk/test/default-timer.conf
platform/linux-dpdk/test/process-mode.conf
platform/linux-dpdk/test/sched-basic.conf
platform/linux-dpdk/test/stash-custom.conf
platform/linux-generic/odp_dma.c

This patchset implements DMA API using `rte_dma_*` API. Implementation tries to find a set of similar capability DMA devices to use as DMA sessions. Certain device(s) can be forced to be discovered with the allowed/blocked devices in `ODP_PLATFORM_PARAMS` environment variable.
Some DPDK dmadev capabilities are lacking and not directly mappable to ODP level DMA capabilities, these should be configured with configuration file parameters.
All completion modes are supported, however, event completion mode is currently implemented synchronously as properly supporting this asynchronously will require support from the scheduling machinery. This will be added later.
v3:
- Matias' comments
v4:
- Changed max transfer dequeue count to take into account maximum in-flight transfer count
v5:
- Matias' …

[PATCH v6] linux-dpdk: implement DMA API

---

platform/linux-dpdk/include/odp_config_internal.h
platform/linux-dpdk/odp_dma.c

Instead of having a separate buffer-backed structure for bookkeeping inflight transfers, use the transfer structures themselves. This removes the need for an additional buffer pool for each DMA session.
Additionally, utilize `<queue.h>` provided iteration macro instead of accessing private fields directly when looping queue structures.
v2:
- Added reviewed-by tag

[PATCH v2] linux-dpdk: dma: simplify inflight transfer bookkeeping

---

test/common/Makefile.am

Instead of depending on presence of `libcunit`, always build `libtest_common`. Otherwise, this will lead to build issues if `libcunit` is not present.

[PATCH v2] test: common: always build libtest_common
